### ISSUE TITLE
pyads.pyads_ex.ADSError: ADSError: target port not found   ADS Server not started (6).

### ISSUE THREAD

**Issue by christojet** [stlehmann/pyads#177]
**This is my code:**
import pyads
plc = pyads.Connection('192.168.10.1.1.1', pyads.PORT_SPS1)
plc.open()
L1 = plc.read_by_name('LBK1Distance', pyads.PLCTYPE_INT)
print(L1)
plc.close()

**This is the error i get:**
Traceback (most recent call last):
  File "pyadsTest.py", line 17, in <module>
    L1 = plc.read_by_name('LBK1Distance', pyads.PLCTYPE_INT)
  File "C:\Users\c.bousquet-jette\AppData\Local\Continuum\anaconda3\envs\ROCAP\lib\site-packages\pyads\ads.py", line 761, in read_by_name
    return adsSyncReadByNameEx(
  File "C:\Users\c.bousquet-jette\AppData\Local\Continuum\anaconda3\envs\ROCAP\lib\site-packages\pyads\pyads_ex.py", line 977, in adsSyncReadByNameEx
    handle = adsGetHandle(port, address, data_name)
  File "C:\Users\c.bousquet-jette\AppData\Local\Continuum\anaconda3\envs\ROCAP\lib\site-packages\pyads\pyads_ex.py", line 770, in adsGetHandle
    handle = adsSyncReadWriteReqEx2(
  File "C:\Users\c.bousquet-jette\AppData\Local\Continuum\anaconda3\envs\ROCAP\lib\site-packages\pyads\pyads_ex.py", line 638, in adsSyncReadWriteReqEx2
    raise ADSError(err_code)
pyads.pyads_ex.ADSError: ADSError: target port not found   ADS Server not started (6).

**This is my TwinCat that show my int variable:**
![image](https://user-images.githubusercontent.com/14008204/103590067-ea7ee380-4eba-11eb-8795-34abbabdef3b.png)

What can i do to read the int value in LBK1Distance?

**Comment by RobertoRoos** [comment]
The error is pretty descriptive: it seems you have the wrong port.

In Visual Studio, to the TwinCAT dropdown and select 'Target Browser' -> 'Target Browser'. In the Ads tab, expand the nodes to find the variable you're looking for. Note the port number of the top node, this is the port you will need to connect.

The value you are looking for is part of a struct? Maybe you could add a simple integer variable next to it and try to read it, just to make sure you can reach the PLC instance.

**Comment by stlehmann** [comment]
@christojet Thanks for reaaching out. We recommend using Stackoverflow for general questions on using pyads and ADS in general. Github issues is for bug reporting and software development so I will close this issue.

**Comment by christojet** [comment]
Hi RobertoRoos,
When i go to the destination you mention, i see that:
![image](https://user-images.githubusercontent.com/14008204/103780121-92eb8f80-5002-11eb-9466-ce6dbec46a0a.png)
Thanks you :)
