### ISSUE TITLE
has python 3.6 support been dropped?

### ISSUE THREAD

**Issue by chrisbeardy** [stlehmann/pyads#285]
I get the follwing error using python 3.6:

```
Traceback (most recent call last):
  File "C:/Users/chrisb/GitWS/pyadsStructureNotificationTest/main.py", line 1, in <module>
    import pyads
  File "C:\Users\chrisb\GitWS\pyadsStructureNotificationTest\venv\lib\site-packages\pyads\__init__.py", line 10, in <module>
    from .ads import (
  File "C:\Users\chrisb\GitWS\pyadsStructureNotificationTest\venv\lib\site-packages\pyads\ads.py", line 8
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Comment by chrisbeardy** [comment]
looks like the last version to support python 3.6 is 3.3.4
