### ISSUE TITLE
Use cp1252 as default encoding for Strings

### ISSUE THREAD

**Issue by stlehmann** [stlehmann/pyads#301]
I've been experimenting now a little bit with the string encoding in Twincat. According to the infosys it's an cp1252 encoding for the normal string. Shouldn't we integrate that one instead of the utf-8?
I tried it with the write_by_name function (adsSyncWriteReqEx) and now you can write with ASCII 256 and the plc shows it the right way.
![Encoding_cp1252](https://user-images.githubusercontent.com/96479552/147059883-eb56fb8c-cf7a-45f4-a3cb-308ace95ad06.jpg)

It doesn't solve my problem with the utf-8 encoded Strings but at least you can write and read special characters with the normal strings.

_Originally posted by @hkalteBr in https://github.com/stlehmann/pyads/issues/300#issuecomment-999379365_

**Comment by joellutz** [comment]
This might be related: Reading a string variable which contains an umlaut (ä,ö,ü etc.) also fails with an exception. Example:

``` ST
MyStringDefault : STRING(255) := 'Hello World';
MyStringWithUmlaut : STRING(255) := 'Hello Wörld';
```

``` python
import pyads
plc = pyads.Connection('199.4.42.250.1.1', pyads.PORT_TC3PLC1)
plc.open()
plc.read_by_name('MyStringDefault', plc_datatype=pyads.PLCTYPE_STRING) # works
plc.read_by_name('MyStringWithUmlaut', plc_datatype=pyads.PLCTYPE_STRING) # UnicodeDecodeError
```

``` 
Traceback (most recent call last):
  File "c:\Temp\umlaute.py", line 8, in <module>
    value = plc.read_by_name(symbol_name_string_umlaut, plc_datatype=pyads.PLCTYPE_STRING)
  File "C:\Program Files\Python310\lib\site-packages\pyads\connection.py", line 546, in read_by_name
    return adsSyncReadByNameEx(
  File "C:\Program Files\Python310\lib\site-packages\pyads\pyads_ex.py", line 1216, in adsSyncReadByNameEx
    value = adsSyncReadReqEx2(
  File "C:\Program Files\Python310\lib\site-packages\pyads\pyads_ex.py", line 882, in adsSyncReadReqEx2
    return get_value_from_ctype_data(data, data_type)
  File "C:\Program Files\Python310\lib\site-packages\pyads\pyads_ex.py", line 264, in get_value_from_ctype_data
    return read_data.value.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 7: invalid start byte
```

This is also the case if the PLC variable is a [T_MaxString](https://infosys.beckhoff.com/index.php?content=../content/1031/tcplclib_tc2_system/31062795.html&id=) and also when using the [TcEncoding](https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_plc_intro/5873680907.html&id=) pragma `{attribute 'TcEncoding':='UTF-8'}`.

Oddly, if the string variable doesn't contain an umlaut, writing and subsequently reading a value with an umlaut _does_ work:

``` python
import pyads
plc = pyads.Connection('199.4.42.250.1.1', pyads.PORT_TC3PLC1)
plc.open()
symbol_name_string_default = 'MyStringDefault'
plc.read_by_name(symbol_name_string_default, plc_datatype=pyads.PLCTYPE_STRING) # works
plc.write_by_name(symbol_name_string_default, 'Hello Wörld', plc_datatype=pyads.PLCTYPE_STRING) # works
plc.read_by_name(symbol_name_string_default, plc_datatype=pyads.PLCTYPE_STRING) # works
```

However, the umlaut doesn't get displayed properly in TwinCAT:

![Image](https://github.com/user-attachments/assets/04ac8808-e30c-48a1-9bff-fa81ede7caf9)
