### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by SmilingWorlock** [stlehmann/pyads#49]
Hi,

my install using pip fails with the following message. I am using Anaconda 5.1.0 and python 3.6.
```

(CONDA_ENV) D:\git\folder>pip install pyads
Collecting pyads
  Using cached https://files.pythonhosted.org/packages/34/8b/a9be7f22408f24e49c8ac38fde82c0b9b084e8fd9ec59fe9141e242f1fe9/pyads-2.2.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-build-qf3ps617\pyads\setup.py", line 133, in <module>
        with open('README.md', 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by stlehmann** [comment]
Thanks for the feedback. Should be fixed by now.
